### ISSUE TITLE
AttributeError: 'ModelManager' object has no attribute 'aitemplates'

### ISSUE THREAD

**Issue by athu16** [db0/AI-Horde#111]
While running horde-bridge.cmd, I get the following error. I'm on the latest build as of 04 January 2023.
```
2023-01-04 19:09:06,226 INFO worker.py:1538 -- Started a local Ray instance.
INIT       | Prepared    | Ray temp dir 'C:\Users\Atharva\Documents\GitHub\nataili\ray'
INIT       | Downloading | Model Reference
INIT       | Download Error | Model Reference
INIT       | Local       | Model Reference
INFO       | 2023-01-04 19:09:49.923417 | nataili.model_manager:init:128 - Highest CUDA Compute Capability: 75
INFO       | 2023-01-04 19:09:49.926392 | nataili.model_manager:init:130 - Recommended GPU: [{'id': 0, 'name': 'NVIDIA GeForce RTX 2060', 'sm': 75}]
INFO       | 2023-01-04 19:09:49.928393 | nataili.model_manager:init:132 - Using sm_75 for AITemplate
Traceback (most recent call last):
  File "bridge.py", line 235, in <module>
    model_manager.init()
  File "C:\Users\Atharva\Documents\GitHub\nataili\nataili\model_manager.py", line 134, in init
    for aitemplate in self.aitemplates:
AttributeError: 'ModelManager' object has no attribute 'aitemplates'
```

UPDATE: I can make the error go away by connecting to a VPN set to USA, but in that case the worker doesn't accept any requests from other users.
I don't understand why it needs to download the Model Reference every time I start the horde.

UPDATE 2: I changed the IPv6 DNS to Google's server, and it works now.

**Comment by athu16** [comment]
If you're facing the same issue, try changing your network's DNS server to Google's, as shown here: https://developers.google.com/speed/public-dns/docs/using
