### ISSUE TITLE
Worker goes in maintenance mode because inpainting jobs with model == CodeFormer

### ISSUE THREAD

**Issue by tijszwinkels** [db0/AI-Horde#133]
Every now and then I enable inpainting on my worker, but it always goes into maintenance mode in a few hours.

From the logs:

```
ERROR      | 2023-01-22 10:21:46.275630 | worker.jobs.stable_diffusion:start_job:267 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': '(comic style), (xray panel), tentacles showing through intestines ### ugly, old, censored, censorship', 'height': 576, 'width': 512, 'seed': '3461815806', 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 30, 'sampler_name': 'k_euler_karras', 'cfg_scale': 7.0, 'denoising_strength': 0.22, 'init_img': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=512x576 at 0x13F7781B280>, 'init_mask': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=512x576 at 0x13F7781BFD0>, 'request_type': 'img2img', 'model': 'CodeFormers'}
TRACE      | 2023-01-22 10:21:46.277631 | worker.jobs.stable_diffusion:start_job:273 - Traceback (most recent call last):
  File "F:\dnn\AI-Horde-Worker\worker\jobs\stable_diffusion.py", line 261, in start_job
    generator.generate(**gen_payload)
  File "F:\dnn\AI-Horde-Worker\nataili\util\performance.py", line 12, in wrapper
    return torch.cuda.amp.autocast()(torch.no_grad()(f))(*args, **kwargs)
  File "F:\dnn\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\amp\autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "F:\dnn\AI-Horde-Worker\conda\envs\windows\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\dnn\AI-Horde-Worker\nataili\inference\compvis.py", line 307, in generate
    with load_from_plasma(self.model, self.device) as model:
  File "F:\dnn\AI-Horde-Worker\conda\envs\windows\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "F:\dnn\AI-Horde-Worker\nataili\util\voodoo.py", line 59, in load_from_plasma
    skeleton, weights = ray.get(ref)
  File "F:\dnn\AI-Horde-Worker\conda\envs\windows\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "F:\dnn\AI-Horde-Worker\conda\envs\windows\lib\site-packages\ray\_private\worker.py", line 2298, in get
    raise ValueError(
ValueError: 'object_refs' must either be an ObjectRef or a list of ObjectRefs.
```

Pay special attention to: `... 'request_type': 'img2img', 'model': 'CodeFormers'}`. CodeFormers is a post-processor, I don't think it should be specified as a model directly.
In the bridge.log, I can see that indeed every img2img (CodeFormers) jobs fails, like:
```
DEBUG      | 2023-01-22 10:35:04.316667 | worker.jobs.stable_diffusion:start_job:159 - img2img (CodeFormers) request with id 1c5dd1b9-32fe-4c44-b9f2-e2a9896696a3 picked up. Initiating work...
DEBUG      | 2023-01-22 10:35:04.323667 | worker.jobs.stable_diffusion:start_job:260 - Starting generation...
ERROR      | 2023-01-22 10:35:04.325666 | worker.jobs.stable_diffusion:start_job:267 - Something went wrong when processing request. Please check your trace.log file for the full stack trace. Payload: {'prompt': 'xray, intestines ### ugly, old, censored, censorship', 'height': 576, 'width': 512, 'seed': '2055393100', 'n_iter': 1, 'batch_size': 1, 'save_individual_images': False, 'save_grid': False, 'ddim_steps': 30, 'sampler_name': 'k_euler_karras', 'cfg_scale': 7.0, 'denoising_strength': 0.22, 'init_img': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=512x576 at 0x13F46B7ED00>, 'init_mask': <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=512x576 at 0x13F46B7EC40>, 'request_type': 'img2img', 'model': 'CodeFormers'}
```

I suspect this would also go wrong for non-inpainting jobs, but I just don't see those. These seem to be occurring in the wild and are putting my worker in maintenance mode.

I was looking whether I can fix this in the worker, but looking in stable_diffusion.py it seems that it just returns on every error. There no difference between 'the request is wrong' or 'I did something wrong' - So perhaps just preventing these faulty requests from ever reaching the worker is a better idea.

We currently have very few inpainting workers. I believe this might be the reason of that.

**Comment by db0** [comment]
I had noticed that as well and I don't get it. It just shouldn't happen

```python
        self.available_models = self.model_manager.get_loaded_models_names()
        for util_model in ["LDSR", "safety_checker", "GFPGAN", "RealESRGAN_x4plus", "CodeFormers"]:
            if util_model in self.available_models:
                self.available_models.remove(util_model)
```

**Comment by tijszwinkels** [comment]
But this suggests a problem worker side, I'll delve further into it tonight or tomorrow.

**Comment by tijszwinkels** [comment]
I got it. See the MR on the worker. :)

**Comment by db0** [comment]
Good catch mate!
