### ISSUE TITLE
Error running it on codespaces

### ISSUE THREAD

**Issue by MrlolDev** [db0/AI-Horde#151]
Error:
```
@MrlolDev ➜ /workspaces/AI-Horde (main) $ python server.py  -vvvvi --horde stable
INIT       | Connecting     | Horde Redis
INIT       | Failed         | Horde Redis
WARNING    | 2023-02-03 07:47:04 | horde.flask:<module>:16 - Using SQLite for database
Traceback (most recent call last):
  File "/workspaces/AI-Horde/server.py", line 7, in <module>
    from horde.argparser import args
  File "/workspaces/AI-Horde/horde/__init__.py", line 10, in <module>
    from horde.routes import *  # I don't like this, we should be refactoring what things are being loaded
  File "/workspaces/AI-Horde/horde/routes.py", line 13, in <module>
    from horde.database import functions as database
  File "/workspaces/AI-Horde/horde/database/__init__.py", line 3, in <module>
    import horde.database.threads as threads
  File "/workspaces/AI-Horde/horde/database/threads.py", line 11, in <module>
    from horde.classes import WaitingPrompt, User, ProcessingGeneration
  File "/workspaces/AI-Horde/horde/classes/__init__.py", line 4, in <module>
    from horde.flask import db, HORDE
  File "/workspaces/AI-Horde/horde/flask.py", line 26, in <module>
    db.init_app(HORDE)
  File "/home/codespace/.local/lib/python3.10/site-packages/flask_sqlalchemy/extension.py", line 253, in init_app
    raise RuntimeError(
RuntimeError: A 'SQLAlchemy' instance has already been registered on this Flask app. Import and use that instance instead.
```

**Comment by db0** [comment]
I don't know what codespaces is or how to fix this for you. It doesn't seem like an issue with this repo
