### ISSUE TITLE
Prevent txt2img requests asking for the stable_diffusion_inpainting model

### ISSUE THREAD

**Issue by CrypticWit** [db0/AI-Horde#70]
I'm currently getting a crash when the stable_diffusion_inpainting model is enabled, along with voodoo.  This is due to receiving the following job:

```
DEBUG      | 2022-11-02 04:43:20 | __main__:bridge:189 - txt2img (stable_diffusion_inpainting) request with id d017d82f-be95-4274-941d-b9fcd6dd2ed3 picked up. Initiating work...
```

The code then crashes in load_from_plasma:

```

ValueError: 'object_refs' must either be an object ref or a list of object refs.
Traceback (most recent call last):
  File "bridge.py", line 447, in <module>
    bridge(args.interval, model_manager, bd)
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/site-packages/logu  ru/_logger.py", line 1220, in catch_wrapper
    return function(*args, **kwargs)
  File "bridge.py", line 247, in bridge
    generator.generate(**gen_payload)
  File "/home/crypticwit/code/SD-Horde-Server/nataili/util/voodoo.py", line 14, in wrapper
    return torch.cuda.amp.autocast()(torch.no_grad()(f))(*args, **kwargs)
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/crypticwit/code/SD-Horde-Server/nataili/inference/compvis/txt2img.py", line 85, in generate
    with load_from_plasma(self.model, self.device) as model:
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/crypticwit/code/SD-Horde-Server/nataili/util/voodoo.py", line 59, in load_from_plasma
    skeleton, weights = ray.get(ref)
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/crypticwit/code/SD-Horde-Server/conda/envs/linux/lib/python3.8/site-packages/ray/_private/worker.py", line 2268, in get
    raise ValueError(
ValueError: 'object_refs' must either be an object ref or a list of object refs.
```

This might need to be fixed in the natalia codebase, but it would be good if the horde protected us from the invalid request until then.

**Comment by db0** [comment]
Normally this shouldn't be possible. Do you load other models along with inpainting?

**Comment by CrypticWit** [comment]
I have been - With a 3090TI, I have about 10gig or so VRAM spare after having both the txt2img and inpainting models loaded, with voodoo activated.

I ran it in that configuration for about a hour last night, and it worked fine until the txt2img request above came through. (doing both txt2img and inpainting jobs).

If we're not supposed to be running both features in parallel on a worker, I might switch my worker to inpainting only, since it seems to be the resource that the horde needs most at the moment.

**Comment by db0** [comment]
I've put some more safety checks which should prevent this happening in the future. Lemme know if you see it happening again after you update your bridge code.
